// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v6.33.1
// source: bl1nk.proto

    /* eslint-disable */
import { BinaryWriter, BinaryReader } from '@bufbuild/protobuf/wire';

export const protobufPackage = 'bl1nk';

export enum RuleTag {
MUST = 0,
SHOULD = 1,
AVOID = 2,
UNRECOGNIZED = -1,
}

export function ruleTagFromJSON(object: any): RuleTag {
switch (object) {
case 0:
      case "MUST":
        return RuleTag.MUST;
case 1:
      case "SHOULD":
        return RuleTag.SHOULD;
case 2:
      case "AVOID":
        return RuleTag.AVOID;
case -1:
        case "UNRECOGNIZED":
        default:
          return RuleTag.UNRECOGNIZED;
}
}

export function ruleTagToJSON(object: RuleTag): string {
switch (object) {
case RuleTag.MUST: return "MUST";
case RuleTag.SHOULD: return "SHOULD";
case RuleTag.AVOID: return "AVOID";
case RuleTag.UNRECOGNIZED:
default:
          return "UNRECOGNIZED";
}
}

export enum MemoryScope {
SCOPE_GLOBAL = 0,
SCOPE_PROJECT = 1,
SCOPE_SESSION = 2,
SCOPE_WORKING = 3,
SCOPE_POLICY = 4,
SCOPE_IDENTITY = 5,
UNRECOGNIZED = -1,
}

export function memoryScopeFromJSON(object: any): MemoryScope {
switch (object) {
case 0:
      case "SCOPE_GLOBAL":
        return MemoryScope.SCOPE_GLOBAL;
case 1:
      case "SCOPE_PROJECT":
        return MemoryScope.SCOPE_PROJECT;
case 2:
      case "SCOPE_SESSION":
        return MemoryScope.SCOPE_SESSION;
case 3:
      case "SCOPE_WORKING":
        return MemoryScope.SCOPE_WORKING;
case 4:
      case "SCOPE_POLICY":
        return MemoryScope.SCOPE_POLICY;
case 5:
      case "SCOPE_IDENTITY":
        return MemoryScope.SCOPE_IDENTITY;
case -1:
        case "UNRECOGNIZED":
        default:
          return MemoryScope.UNRECOGNIZED;
}
}

export function memoryScopeToJSON(object: MemoryScope): string {
switch (object) {
case MemoryScope.SCOPE_GLOBAL: return "SCOPE_GLOBAL";
case MemoryScope.SCOPE_PROJECT: return "SCOPE_PROJECT";
case MemoryScope.SCOPE_SESSION: return "SCOPE_SESSION";
case MemoryScope.SCOPE_WORKING: return "SCOPE_WORKING";
case MemoryScope.SCOPE_POLICY: return "SCOPE_POLICY";
case MemoryScope.SCOPE_IDENTITY: return "SCOPE_IDENTITY";
case MemoryScope.UNRECOGNIZED:
default:
          return "UNRECOGNIZED";
}
}

export enum MemoryCategory {
CATEGORY_FACT = 0,
CATEGORY_PREFERENCE = 1,
CATEGORY_HISTORY = 2,
CATEGORY_CONTEXT = 3,
CATEGORY_INFERENCE = 4,
UNRECOGNIZED = -1,
}

export function memoryCategoryFromJSON(object: any): MemoryCategory {
switch (object) {
case 0:
      case "CATEGORY_FACT":
        return MemoryCategory.CATEGORY_FACT;
case 1:
      case "CATEGORY_PREFERENCE":
        return MemoryCategory.CATEGORY_PREFERENCE;
case 2:
      case "CATEGORY_HISTORY":
        return MemoryCategory.CATEGORY_HISTORY;
case 3:
      case "CATEGORY_CONTEXT":
        return MemoryCategory.CATEGORY_CONTEXT;
case 4:
      case "CATEGORY_INFERENCE":
        return MemoryCategory.CATEGORY_INFERENCE;
case -1:
        case "UNRECOGNIZED":
        default:
          return MemoryCategory.UNRECOGNIZED;
}
}

export function memoryCategoryToJSON(object: MemoryCategory): string {
switch (object) {
case MemoryCategory.CATEGORY_FACT: return "CATEGORY_FACT";
case MemoryCategory.CATEGORY_PREFERENCE: return "CATEGORY_PREFERENCE";
case MemoryCategory.CATEGORY_HISTORY: return "CATEGORY_HISTORY";
case MemoryCategory.CATEGORY_CONTEXT: return "CATEGORY_CONTEXT";
case MemoryCategory.CATEGORY_INFERENCE: return "CATEGORY_INFERENCE";
case MemoryCategory.UNRECOGNIZED:
default:
          return "UNRECOGNIZED";
}
}

export enum PromptBlockType {
BLOCK_SYSTEM = 0,
BLOCK_POLICY = 1,
BLOCK_IDENTITY = 2,
BLOCK_MEMORY = 3,
BLOCK_TASK = 4,
BLOCK_TOOL_INSTRUCTION = 5,
BLOCK_PLAN = 6,
BLOCK_USER_INPUT = 7,
BLOCK_GUARDRAIL = 8,
BLOCK_OUTPUT_FORMAT = 9,
UNRECOGNIZED = -1,
}

export function promptBlockTypeFromJSON(object: any): PromptBlockType {
switch (object) {
case 0:
      case "BLOCK_SYSTEM":
        return PromptBlockType.BLOCK_SYSTEM;
case 1:
      case "BLOCK_POLICY":
        return PromptBlockType.BLOCK_POLICY;
case 2:
      case "BLOCK_IDENTITY":
        return PromptBlockType.BLOCK_IDENTITY;
case 3:
      case "BLOCK_MEMORY":
        return PromptBlockType.BLOCK_MEMORY;
case 4:
      case "BLOCK_TASK":
        return PromptBlockType.BLOCK_TASK;
case 5:
      case "BLOCK_TOOL_INSTRUCTION":
        return PromptBlockType.BLOCK_TOOL_INSTRUCTION;
case 6:
      case "BLOCK_PLAN":
        return PromptBlockType.BLOCK_PLAN;
case 7:
      case "BLOCK_USER_INPUT":
        return PromptBlockType.BLOCK_USER_INPUT;
case 8:
      case "BLOCK_GUARDRAIL":
        return PromptBlockType.BLOCK_GUARDRAIL;
case 9:
      case "BLOCK_OUTPUT_FORMAT":
        return PromptBlockType.BLOCK_OUTPUT_FORMAT;
case -1:
        case "UNRECOGNIZED":
        default:
          return PromptBlockType.UNRECOGNIZED;
}
}

export function promptBlockTypeToJSON(object: PromptBlockType): string {
switch (object) {
case PromptBlockType.BLOCK_SYSTEM: return "BLOCK_SYSTEM";
case PromptBlockType.BLOCK_POLICY: return "BLOCK_POLICY";
case PromptBlockType.BLOCK_IDENTITY: return "BLOCK_IDENTITY";
case PromptBlockType.BLOCK_MEMORY: return "BLOCK_MEMORY";
case PromptBlockType.BLOCK_TASK: return "BLOCK_TASK";
case PromptBlockType.BLOCK_TOOL_INSTRUCTION: return "BLOCK_TOOL_INSTRUCTION";
case PromptBlockType.BLOCK_PLAN: return "BLOCK_PLAN";
case PromptBlockType.BLOCK_USER_INPUT: return "BLOCK_USER_INPUT";
case PromptBlockType.BLOCK_GUARDRAIL: return "BLOCK_GUARDRAIL";
case PromptBlockType.BLOCK_OUTPUT_FORMAT: return "BLOCK_OUTPUT_FORMAT";
case PromptBlockType.UNRECOGNIZED:
default:
          return "UNRECOGNIZED";
}
}

export interface Category {
id: number,
key: string,
label: string,
icon: string,
orderIndex: number,
}

export interface Section {
id: number,
categoryId: number,
title: string,
icon: string,
color: string,
textColor: string,
orderIndex: number,
}

export interface Rule {
id: number,
sectionId: number,
text: string,
tag: RuleTag,
code?: string | undefined,
orderIndex: number,
isCustom: boolean,
userId?: string | undefined,
}

export interface UserProgress {
userId: string,
ruleId: number,
checked: boolean,
}

export interface RuleList {
rules: Rule[],
}

export interface MemoryEntry {
id: string,
scope: MemoryScope,
category: MemoryCategory,
key: string,
value: string,
/** provenance: where this came from */
source: string,
/** 0.0 .. 1.0 */
confidence: number,
/** Unix timestamp */
createdAt: string,
updatedAt: string,
version: number,
/** "active", "archived", "expired" */
status: string,
tags: string[],
/** user_id if scoped to user */
owner?: string | undefined,
/** "public", "project", "private", "secret" */
accessLevel: string,
/** detailed source metadata (JSON) */
provenance?: string | undefined,
/** Unix timestamp, optional TTL */
expiresAt?: string | undefined,
}

export interface MemoryLink {
id: string,
fromEntryId: string,
toEntryId: string,
/** "references", "depends_on", "contradicts", etc. */
relationType: string,
/** JSON */
metadata?: string | undefined,
}

export interface MemoryAuditLog {
id: string,
entryId: string,
/** "insert", "update", "delete", "link" */
operation: string,
/** user_id or "system" */
performedBy: string,
timestamp: string,
oldValue?: string | undefined,
newValue?: string | undefined,
}

export interface PromptBlock {
id: string,
type: PromptBlockType,
/** 1 (highest) to 10 (lowest) */
priority: number,
scope: MemoryScope,
content: string,
/** provenance */
source: string,
/** JSON: token_limit, must_include, etc. */
constraints?: string | undefined,
/** block IDs this depends on */
dependencies: string[],
version: number,
}

export interface ContextPack {
sessionId: string,
/** ordered by priority */
blocks: PromptBlock[],
assembledAt: string,
traceId?: string | undefined,
totalTokensEstimate: number,
}

export interface ConflictRecord {
id: string,
/** JSON array */
conflictingBlockIds: string,
/** "scope_violation", "rule_violation", "priority_inversion" */
conflictType: string,
description: string,
/** "first_wins", "higher_priority", "manual" */
resolution: string,
/** user_id or "system" */
resolvedBy: string,
resolvedAt: string,
isResolved: boolean,
}

export interface PolicyRule {
id: string,
/** "hard", "soft", "context", "safety" */
ruleType: string,
name: string,
description: string,
/** JSONLogic or custom DSL */
condition: string,
/** "allow", "deny", "modify", "flag" */
action: string,
/** evaluation order */
priority: number,
/** which scopes this applies to */
scope: string,
enabled: boolean,
effectiveFrom: string,
effectiveUntil?: string | undefined,
}

export interface PolicyEvaluation {
contextId: string,
ruleId: string,
allowed: boolean,
/** JSON of suggested changes */
modification: string,
reason: string,
}

export interface TestCase {
id: string,
/** "unit", "integration", "e2e", "edge" */
type: string,
title: string,
description: string,
precondition: string,
/** Markdown or JSON array */
steps: string,
expectedResult: string,
/** links to workflow step */
relatedStepId: string,
/** minutes */
estimatedDuration: number,
}

export interface TestSuite {
id: string,
name: string,
testCaseIds: string[],
}

export interface TestPlan {
id: string,
templateId: string,
version: string,
suites: TestSuite[],
/** keyed by id */
testCases: { [key: string ]: TestCase },
/** e.g., 0.8 for 80% */
coverageTarget: number,
generatedBy: string,
generatedAt: string,
llmModelUsed?: string | undefined,
}

export interface TestPlan_TestCasesEntry {
key: string,
value: TestCase | undefined,
}

export interface WorkInstruction {
id: string,
templateId: string,
testPlanId: string,
/** "markdown", "json", "html" */
format: string,
/** rendered document */
content: string,
version: string,
createdAt: string,
approvedBy?: string | undefined,
approvedAt?: string | undefined,
}

function createBaseCategory(): Category {
      return { id: 0,key: "",label: "",icon: "",orderIndex: 0 };
    }

export const Category: MessageFns<Category> = {
              encode(
      message: Category,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
if ( message.id !== 0) {
          writer.uint32(8).int32(message.id);
        }
if ( message.key !== "") {
          writer.uint32(18).string(message.key);
        }
if ( message.label !== "") {
          writer.uint32(26).string(message.label);
        }
if ( message.icon !== "") {
          writer.uint32(34).string(message.icon);
        }
if ( message.orderIndex !== 0) {
          writer.uint32(40).int32(message.orderIndex);
        }
return writer;
},

decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): Category {
      const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
const message = createBaseCategory();
while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
case 1: {
if (tag !== 8) {
        break;
      }
    
        message.id = reader.int32();
continue; }
case 2: {
if (tag !== 18) {
        break;
      }
    
        message.key = reader.string();
continue; }
case 3: {
if (tag !== 26) {
        break;
      }
    
        message.label = reader.string();
continue; }
case 4: {
if (tag !== 34) {
        break;
      }
    
        message.icon = reader.string();
continue; }
case 5: {
if (tag !== 40) {
        break;
      }
    
        message.orderIndex = reader.int32();
continue; }
}
if ((tag & 7) === 4 || tag === 0) {
        break;
      }
reader.skip(tag & 7);
}
return message;
},

fromJSON(object: any): Category {
      return {
id: isSet(object.id) ? globalThis.Number(object.id)
        
          : 0,
key: isSet(object.key) ? globalThis.String(object.key)
        
          : "",
label: isSet(object.label) ? globalThis.String(object.label)
        
          : "",
icon: isSet(object.icon) ? globalThis.String(object.icon)
        
          : "",
orderIndex: isSet(object.orderIndex) ? globalThis.Number(object.orderIndex)
         : isSet(object.order_index) ? globalThis.Number(object.order_index)
          : 0,
};
},

toJSON(message: Category): unknown {
      const obj: any = {};
if ( message.id !== 0) {
          obj.id = Math.round(message.id);
        }
if ( message.key !== "") {
          obj.key = message.key;
        }
if ( message.label !== "") {
          obj.label = message.label;
        }
if ( message.icon !== "") {
          obj.icon = message.icon;
        }
if ( message.orderIndex !== 0) {
          obj.orderIndex = Math.round(message.orderIndex);
        }
return obj;
},

create<I extends Exact<DeepPartial<Category>, I>>(base?: I): Category {
        return Category.fromPartial(base ?? ({} as any));
      },
fromPartial<I extends Exact<DeepPartial<Category>, I>>(object: I): Category {
const message = createBaseCategory();
message.id = object.id ?? 0;
message.key = object.key ?? "";
message.label = object.label ?? "";
message.icon = object.icon ?? "";
message.orderIndex = object.orderIndex ?? 0;
return message;
}
            };

function createBaseSection(): Section {
      return { id: 0,categoryId: 0,title: "",icon: "",color: "",textColor: "",orderIndex: 0 };
    }

export const Section: MessageFns<Section> = {
              encode(
      message: Section,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
if ( message.id !== 0) {
          writer.uint32(8).int32(message.id);
        }
if ( message.categoryId !== 0) {
          writer.uint32(16).int32(message.categoryId);
        }
if ( message.title !== "") {
          writer.uint32(26).string(message.title);
        }
if ( message.icon !== "") {
          writer.uint32(34).string(message.icon);
        }
if ( message.color !== "") {
          writer.uint32(42).string(message.color);
        }
if ( message.textColor !== "") {
          writer.uint32(50).string(message.textColor);
        }
if ( message.orderIndex !== 0) {
          writer.uint32(56).int32(message.orderIndex);
        }
return writer;
},

decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): Section {
      const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
const message = createBaseSection();
while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
case 1: {
if (tag !== 8) {
        break;
      }
    
        message.id = reader.int32();
continue; }
case 2: {
if (tag !== 16) {
        break;
      }
    
        message.categoryId = reader.int32();
continue; }
case 3: {
if (tag !== 26) {
        break;
      }
    
        message.title = reader.string();
continue; }
case 4: {
if (tag !== 34) {
        break;
      }
    
        message.icon = reader.string();
continue; }
case 5: {
if (tag !== 42) {
        break;
      }
    
        message.color = reader.string();
continue; }
case 6: {
if (tag !== 50) {
        break;
      }
    
        message.textColor = reader.string();
continue; }
case 7: {
if (tag !== 56) {
        break;
      }
    
        message.orderIndex = reader.int32();
continue; }
}
if ((tag & 7) === 4 || tag === 0) {
        break;
      }
reader.skip(tag & 7);
}
return message;
},

fromJSON(object: any): Section {
      return {
id: isSet(object.id) ? globalThis.Number(object.id)
        
          : 0,
categoryId: isSet(object.categoryId) ? globalThis.Number(object.categoryId)
         : isSet(object.category_id) ? globalThis.Number(object.category_id)
          : 0,
title: isSet(object.title) ? globalThis.String(object.title)
        
          : "",
icon: isSet(object.icon) ? globalThis.String(object.icon)
        
          : "",
color: isSet(object.color) ? globalThis.String(object.color)
        
          : "",
textColor: isSet(object.textColor) ? globalThis.String(object.textColor)
         : isSet(object.text_color) ? globalThis.String(object.text_color)
          : "",
orderIndex: isSet(object.orderIndex) ? globalThis.Number(object.orderIndex)
         : isSet(object.order_index) ? globalThis.Number(object.order_index)
          : 0,
};
},

toJSON(message: Section): unknown {
      const obj: any = {};
if ( message.id !== 0) {
          obj.id = Math.round(message.id);
        }
if ( message.categoryId !== 0) {
          obj.categoryId = Math.round(message.categoryId);
        }
if ( message.title !== "") {
          obj.title = message.title;
        }
if ( message.icon !== "") {
          obj.icon = message.icon;
        }
if ( message.color !== "") {
          obj.color = message.color;
        }
if ( message.textColor !== "") {
          obj.textColor = message.textColor;
        }
if ( message.orderIndex !== 0) {
          obj.orderIndex = Math.round(message.orderIndex);
        }
return obj;
},

create<I extends Exact<DeepPartial<Section>, I>>(base?: I): Section {
        return Section.fromPartial(base ?? ({} as any));
      },
fromPartial<I extends Exact<DeepPartial<Section>, I>>(object: I): Section {
const message = createBaseSection();
message.id = object.id ?? 0;
message.categoryId = object.categoryId ?? 0;
message.title = object.title ?? "";
message.icon = object.icon ?? "";
message.color = object.color ?? "";
message.textColor = object.textColor ?? "";
message.orderIndex = object.orderIndex ?? 0;
return message;
}
            };

function createBaseRule(): Rule {
      return { id: 0,sectionId: 0,text: "",tag: 0,code: undefined,orderIndex: 0,isCustom: false,userId: undefined };
    }

export const Rule: MessageFns<Rule> = {
              encode(
      message: Rule,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
if ( message.id !== 0) {
          writer.uint32(8).int32(message.id);
        }
if ( message.sectionId !== 0) {
          writer.uint32(16).int32(message.sectionId);
        }
if ( message.text !== "") {
          writer.uint32(26).string(message.text);
        }
if ( message.tag !== 0) {
          writer.uint32(32).int32(message.tag);
        }
if (message.code !== undefined ) {
          writer.uint32(42).string(message.code);
        }
if ( message.orderIndex !== 0) {
          writer.uint32(48).int32(message.orderIndex);
        }
if ( message.isCustom !== false) {
          writer.uint32(56).bool(message.isCustom);
        }
if (message.userId !== undefined ) {
          writer.uint32(66).string(message.userId);
        }
return writer;
},

decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): Rule {
      const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
const message = createBaseRule();
while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
case 1: {
if (tag !== 8) {
        break;
      }
    
        message.id = reader.int32();
continue; }
case 2: {
if (tag !== 16) {
        break;
      }
    
        message.sectionId = reader.int32();
continue; }
case 3: {
if (tag !== 26) {
        break;
      }
    
        message.text = reader.string();
continue; }
case 4: {
if (tag !== 32) {
        break;
      }
    
        message.tag = reader.int32() as any;
continue; }
case 5: {
if (tag !== 42) {
        break;
      }
    
        message.code = reader.string();
continue; }
case 6: {
if (tag !== 48) {
        break;
      }
    
        message.orderIndex = reader.int32();
continue; }
case 7: {
if (tag !== 56) {
        break;
      }
    
        message.isCustom = reader.bool();
continue; }
case 8: {
if (tag !== 66) {
        break;
      }
    
        message.userId = reader.string();
continue; }
}
if ((tag & 7) === 4 || tag === 0) {
        break;
      }
reader.skip(tag & 7);
}
return message;
},

fromJSON(object: any): Rule {
      return {
id: isSet(object.id) ? globalThis.Number(object.id)
        
          : 0,
sectionId: isSet(object.sectionId) ? globalThis.Number(object.sectionId)
         : isSet(object.section_id) ? globalThis.Number(object.section_id)
          : 0,
text: isSet(object.text) ? globalThis.String(object.text)
        
          : "",
tag: isSet(object.tag) ? ruleTagFromJSON(object.tag)
        
          : 0,
code: isSet(object.code) ? globalThis.String(object.code)
        
          : undefined,
orderIndex: isSet(object.orderIndex) ? globalThis.Number(object.orderIndex)
         : isSet(object.order_index) ? globalThis.Number(object.order_index)
          : 0,
isCustom: isSet(object.isCustom) ? globalThis.Boolean(object.isCustom)
         : isSet(object.is_custom) ? globalThis.Boolean(object.is_custom)
          : false,
userId: isSet(object.userId) ? globalThis.String(object.userId)
         : isSet(object.user_id) ? globalThis.String(object.user_id)
          : undefined,
};
},

toJSON(message: Rule): unknown {
      const obj: any = {};
if ( message.id !== 0) {
          obj.id = Math.round(message.id);
        }
if ( message.sectionId !== 0) {
          obj.sectionId = Math.round(message.sectionId);
        }
if ( message.text !== "") {
          obj.text = message.text;
        }
if ( message.tag !== 0) {
          obj.tag = ruleTagToJSON(message.tag);
        }
if (message.code !== undefined ) {
          obj.code = message.code;
        }
if ( message.orderIndex !== 0) {
          obj.orderIndex = Math.round(message.orderIndex);
        }
if ( message.isCustom !== false) {
          obj.isCustom = message.isCustom;
        }
if (message.userId !== undefined ) {
          obj.userId = message.userId;
        }
return obj;
},

create<I extends Exact<DeepPartial<Rule>, I>>(base?: I): Rule {
        return Rule.fromPartial(base ?? ({} as any));
      },
fromPartial<I extends Exact<DeepPartial<Rule>, I>>(object: I): Rule {
const message = createBaseRule();
message.id = object.id ?? 0;
message.sectionId = object.sectionId ?? 0;
message.text = object.text ?? "";
message.tag = object.tag ?? 0;
message.code = object.code ?? undefined;
message.orderIndex = object.orderIndex ?? 0;
message.isCustom = object.isCustom ?? false;
message.userId = object.userId ?? undefined;
return message;
}
            };

function createBaseUserProgress(): UserProgress {
      return { userId: "",ruleId: 0,checked: false };
    }

export const UserProgress: MessageFns<UserProgress> = {
              encode(
      message: UserProgress,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
if ( message.userId !== "") {
          writer.uint32(10).string(message.userId);
        }
if ( message.ruleId !== 0) {
          writer.uint32(16).int32(message.ruleId);
        }
if ( message.checked !== false) {
          writer.uint32(24).bool(message.checked);
        }
return writer;
},

decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): UserProgress {
      const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
const message = createBaseUserProgress();
while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
case 1: {
if (tag !== 10) {
        break;
      }
    
        message.userId = reader.string();
continue; }
case 2: {
if (tag !== 16) {
        break;
      }
    
        message.ruleId = reader.int32();
continue; }
case 3: {
if (tag !== 24) {
        break;
      }
    
        message.checked = reader.bool();
continue; }
}
if ((tag & 7) === 4 || tag === 0) {
        break;
      }
reader.skip(tag & 7);
}
return message;
},

fromJSON(object: any): UserProgress {
      return {
userId: isSet(object.userId) ? globalThis.String(object.userId)
         : isSet(object.user_id) ? globalThis.String(object.user_id)
          : "",
ruleId: isSet(object.ruleId) ? globalThis.Number(object.ruleId)
         : isSet(object.rule_id) ? globalThis.Number(object.rule_id)
          : 0,
checked: isSet(object.checked) ? globalThis.Boolean(object.checked)
        
          : false,
};
},

toJSON(message: UserProgress): unknown {
      const obj: any = {};
if ( message.userId !== "") {
          obj.userId = message.userId;
        }
if ( message.ruleId !== 0) {
          obj.ruleId = Math.round(message.ruleId);
        }
if ( message.checked !== false) {
          obj.checked = message.checked;
        }
return obj;
},

create<I extends Exact<DeepPartial<UserProgress>, I>>(base?: I): UserProgress {
        return UserProgress.fromPartial(base ?? ({} as any));
      },
fromPartial<I extends Exact<DeepPartial<UserProgress>, I>>(object: I): UserProgress {
const message = createBaseUserProgress();
message.userId = object.userId ?? "";
message.ruleId = object.ruleId ?? 0;
message.checked = object.checked ?? false;
return message;
}
            };

function createBaseRuleList(): RuleList {
      return { rules: [] };
    }

export const RuleList: MessageFns<RuleList> = {
              encode(
      message: RuleList,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
for (const v of message.rules) {
            Rule.encode(v!, writer.uint32(10).fork()).join();
          }
return writer;
},

decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): RuleList {
      const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
const message = createBaseRuleList();
while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
case 1: {
if (tag !== 10) {
        break;
      }
    
              
              message.rules.push(Rule.decode(reader, reader.uint32()));
continue; }
}
if ((tag & 7) === 4 || tag === 0) {
        break;
      }
reader.skip(tag & 7);
}
return message;
},

fromJSON(object: any): RuleList {
      return {
rules: globalThis.Array.isArray(object?.rules) ? object.rules.map((e: any) => Rule.fromJSON(e))  : [],
};
},

toJSON(message: RuleList): unknown {
      const obj: any = {};
if (message.rules?.length) {
          obj.rules = message.rules.map(e => Rule.toJSON(e));
        }
return obj;
},

create<I extends Exact<DeepPartial<RuleList>, I>>(base?: I): RuleList {
        return RuleList.fromPartial(base ?? ({} as any));
      },
fromPartial<I extends Exact<DeepPartial<RuleList>, I>>(object: I): RuleList {
const message = createBaseRuleList();
message.rules = object.rules?.map((e) => Rule.fromPartial(e)) || [];
return message;
}
            };

function createBaseMemoryEntry(): MemoryEntry {
      return { id: "0",scope: 0,category: 0,key: "",value: "",source: "",confidence: 0,createdAt: "0",updatedAt: "0",version: 0,status: "",tags: [],owner: undefined,accessLevel: "",provenance: undefined,expiresAt: undefined };
    }

export const MemoryEntry: MessageFns<MemoryEntry> = {
              encode(
      message: MemoryEntry,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
if ( message.id !== "0") {
          writer.uint32(8).int64(message.id);
        }
if ( message.scope !== 0) {
          writer.uint32(16).int32(message.scope);
        }
if ( message.category !== 0) {
          writer.uint32(24).int32(message.category);
        }
if ( message.key !== "") {
          writer.uint32(34).string(message.key);
        }
if ( message.value !== "") {
          writer.uint32(42).string(message.value);
        }
if ( message.source !== "") {
          writer.uint32(50).string(message.source);
        }
if ( message.confidence !== 0) {
          writer.uint32(61).float(message.confidence);
        }
if ( message.createdAt !== "0") {
          writer.uint32(64).int64(message.createdAt);
        }
if ( message.updatedAt !== "0") {
          writer.uint32(72).int64(message.updatedAt);
        }
if ( message.version !== 0) {
          writer.uint32(80).int32(message.version);
        }
if ( message.status !== "") {
          writer.uint32(90).string(message.status);
        }
for (const v of message.tags) {
            writer.uint32(98).string(v!);
          }
if (message.owner !== undefined ) {
          writer.uint32(106).string(message.owner);
        }
if ( message.accessLevel !== "") {
          writer.uint32(114).string(message.accessLevel);
        }
if (message.provenance !== undefined ) {
          writer.uint32(122).string(message.provenance);
        }
if (message.expiresAt !== undefined ) {
          writer.uint32(128).int64(message.expiresAt);
        }
return writer;
},

decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): MemoryEntry {
      const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
const message = createBaseMemoryEntry();
while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
case 1: {
if (tag !== 8) {
        break;
      }
    
        message.id = reader.int64().toString();
continue; }
case 2: {
if (tag !== 16) {
        break;
      }
    
        message.scope = reader.int32() as any;
continue; }
case 3: {
if (tag !== 24) {
        break;
      }
    
        message.category = reader.int32() as any;
continue; }
case 4: {
if (tag !== 34) {
        break;
      }
    
        message.key = reader.string();
continue; }
case 5: {
if (tag !== 42) {
        break;
      }
    
        message.value = reader.string();
continue; }
case 6: {
if (tag !== 50) {
        break;
      }
    
        message.source = reader.string();
continue; }
case 7: {
if (tag !== 61) {
        break;
      }
    
        message.confidence = reader.float();
continue; }
case 8: {
if (tag !== 64) {
        break;
      }
    
        message.createdAt = reader.int64().toString();
continue; }
case 9: {
if (tag !== 72) {
        break;
      }
    
        message.updatedAt = reader.int64().toString();
continue; }
case 10: {
if (tag !== 80) {
        break;
      }
    
        message.version = reader.int32();
continue; }
case 11: {
if (tag !== 90) {
        break;
      }
    
        message.status = reader.string();
continue; }
case 12: {
if (tag !== 98) {
        break;
      }
    
              
              message.tags.push(reader.string());
continue; }
case 13: {
if (tag !== 106) {
        break;
      }
    
        message.owner = reader.string();
continue; }
case 14: {
if (tag !== 114) {
        break;
      }
    
        message.accessLevel = reader.string();
continue; }
case 15: {
if (tag !== 122) {
        break;
      }
    
        message.provenance = reader.string();
continue; }
case 16: {
if (tag !== 128) {
        break;
      }
    
        message.expiresAt = reader.int64().toString();
continue; }
}
if ((tag & 7) === 4 || tag === 0) {
        break;
      }
reader.skip(tag & 7);
}
return message;
},

fromJSON(object: any): MemoryEntry {
      return {
id: isSet(object.id) ? globalThis.String(object.id)
        
          : "0",
scope: isSet(object.scope) ? memoryScopeFromJSON(object.scope)
        
          : 0,
category: isSet(object.category) ? memoryCategoryFromJSON(object.category)
        
          : 0,
key: isSet(object.key) ? globalThis.String(object.key)
        
          : "",
value: isSet(object.value) ? globalThis.String(object.value)
        
          : "",
source: isSet(object.source) ? globalThis.String(object.source)
        
          : "",
confidence: isSet(object.confidence) ? globalThis.Number(object.confidence)
        
          : 0,
createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt)
         : isSet(object.created_at) ? globalThis.String(object.created_at)
          : "0",
updatedAt: isSet(object.updatedAt) ? globalThis.String(object.updatedAt)
         : isSet(object.updated_at) ? globalThis.String(object.updated_at)
          : "0",
version: isSet(object.version) ? globalThis.Number(object.version)
        
          : 0,
status: isSet(object.status) ? globalThis.String(object.status)
        
          : "",
tags: globalThis.Array.isArray(object?.tags) ? object.tags.map((e: any) => globalThis.String(e))  : [],
owner: isSet(object.owner) ? globalThis.String(object.owner)
        
          : undefined,
accessLevel: isSet(object.accessLevel) ? globalThis.String(object.accessLevel)
         : isSet(object.access_level) ? globalThis.String(object.access_level)
          : "",
provenance: isSet(object.provenance) ? globalThis.String(object.provenance)
        
          : undefined,
expiresAt: isSet(object.expiresAt) ? globalThis.String(object.expiresAt)
         : isSet(object.expires_at) ? globalThis.String(object.expires_at)
          : undefined,
};
},

toJSON(message: MemoryEntry): unknown {
      const obj: any = {};
if ( message.id !== "0") {
          obj.id = message.id;
        }
if ( message.scope !== 0) {
          obj.scope = memoryScopeToJSON(message.scope);
        }
if ( message.category !== 0) {
          obj.category = memoryCategoryToJSON(message.category);
        }
if ( message.key !== "") {
          obj.key = message.key;
        }
if ( message.value !== "") {
          obj.value = message.value;
        }
if ( message.source !== "") {
          obj.source = message.source;
        }
if ( message.confidence !== 0) {
          obj.confidence = message.confidence;
        }
if ( message.createdAt !== "0") {
          obj.createdAt = message.createdAt;
        }
if ( message.updatedAt !== "0") {
          obj.updatedAt = message.updatedAt;
        }
if ( message.version !== 0) {
          obj.version = Math.round(message.version);
        }
if ( message.status !== "") {
          obj.status = message.status;
        }
if (message.tags?.length) {
          obj.tags = message.tags;
        }
if (message.owner !== undefined ) {
          obj.owner = message.owner;
        }
if ( message.accessLevel !== "") {
          obj.accessLevel = message.accessLevel;
        }
if (message.provenance !== undefined ) {
          obj.provenance = message.provenance;
        }
if (message.expiresAt !== undefined ) {
          obj.expiresAt = message.expiresAt;
        }
return obj;
},

create<I extends Exact<DeepPartial<MemoryEntry>, I>>(base?: I): MemoryEntry {
        return MemoryEntry.fromPartial(base ?? ({} as any));
      },
fromPartial<I extends Exact<DeepPartial<MemoryEntry>, I>>(object: I): MemoryEntry {
const message = createBaseMemoryEntry();
message.id = object.id ?? "0";
message.scope = object.scope ?? 0;
message.category = object.category ?? 0;
message.key = object.key ?? "";
message.value = object.value ?? "";
message.source = object.source ?? "";
message.confidence = object.confidence ?? 0;
message.createdAt = object.createdAt ?? "0";
message.updatedAt = object.updatedAt ?? "0";
message.version = object.version ?? 0;
message.status = object.status ?? "";
message.tags = object.tags?.map((e) => e) || [];
message.owner = object.owner ?? undefined;
message.accessLevel = object.accessLevel ?? "";
message.provenance = object.provenance ?? undefined;
message.expiresAt = object.expiresAt ?? undefined;
return message;
}
            };

function createBaseMemoryLink(): MemoryLink {
      return { id: "0",fromEntryId: "0",toEntryId: "0",relationType: "",metadata: undefined };
    }

export const MemoryLink: MessageFns<MemoryLink> = {
              encode(
      message: MemoryLink,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
if ( message.id !== "0") {
          writer.uint32(8).int64(message.id);
        }
if ( message.fromEntryId !== "0") {
          writer.uint32(16).int64(message.fromEntryId);
        }
if ( message.toEntryId !== "0") {
          writer.uint32(24).int64(message.toEntryId);
        }
if ( message.relationType !== "") {
          writer.uint32(34).string(message.relationType);
        }
if (message.metadata !== undefined ) {
          writer.uint32(42).string(message.metadata);
        }
return writer;
},

decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): MemoryLink {
      const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
const message = createBaseMemoryLink();
while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
case 1: {
if (tag !== 8) {
        break;
      }
    
        message.id = reader.int64().toString();
continue; }
case 2: {
if (tag !== 16) {
        break;
      }
    
        message.fromEntryId = reader.int64().toString();
continue; }
case 3: {
if (tag !== 24) {
        break;
      }
    
        message.toEntryId = reader.int64().toString();
continue; }
case 4: {
if (tag !== 34) {
        break;
      }
    
        message.relationType = reader.string();
continue; }
case 5: {
if (tag !== 42) {
        break;
      }
    
        message.metadata = reader.string();
continue; }
}
if ((tag & 7) === 4 || tag === 0) {
        break;
      }
reader.skip(tag & 7);
}
return message;
},

fromJSON(object: any): MemoryLink {
      return {
id: isSet(object.id) ? globalThis.String(object.id)
        
          : "0",
fromEntryId: isSet(object.fromEntryId) ? globalThis.String(object.fromEntryId)
         : isSet(object.from_entry_id) ? globalThis.String(object.from_entry_id)
          : "0",
toEntryId: isSet(object.toEntryId) ? globalThis.String(object.toEntryId)
         : isSet(object.to_entry_id) ? globalThis.String(object.to_entry_id)
          : "0",
relationType: isSet(object.relationType) ? globalThis.String(object.relationType)
         : isSet(object.relation_type) ? globalThis.String(object.relation_type)
          : "",
metadata: isSet(object.metadata) ? globalThis.String(object.metadata)
        
          : undefined,
};
},

toJSON(message: MemoryLink): unknown {
      const obj: any = {};
if ( message.id !== "0") {
          obj.id = message.id;
        }
if ( message.fromEntryId !== "0") {
          obj.fromEntryId = message.fromEntryId;
        }
if ( message.toEntryId !== "0") {
          obj.toEntryId = message.toEntryId;
        }
if ( message.relationType !== "") {
          obj.relationType = message.relationType;
        }
if (message.metadata !== undefined ) {
          obj.metadata = message.metadata;
        }
return obj;
},

create<I extends Exact<DeepPartial<MemoryLink>, I>>(base?: I): MemoryLink {
        return MemoryLink.fromPartial(base ?? ({} as any));
      },
fromPartial<I extends Exact<DeepPartial<MemoryLink>, I>>(object: I): MemoryLink {
const message = createBaseMemoryLink();
message.id = object.id ?? "0";
message.fromEntryId = object.fromEntryId ?? "0";
message.toEntryId = object.toEntryId ?? "0";
message.relationType = object.relationType ?? "";
message.metadata = object.metadata ?? undefined;
return message;
}
            };

function createBaseMemoryAuditLog(): MemoryAuditLog {
      return { id: "0",entryId: "0",operation: "",performedBy: "",timestamp: "0",oldValue: undefined,newValue: undefined };
    }

export const MemoryAuditLog: MessageFns<MemoryAuditLog> = {
              encode(
      message: MemoryAuditLog,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
if ( message.id !== "0") {
          writer.uint32(8).int64(message.id);
        }
if ( message.entryId !== "0") {
          writer.uint32(16).int64(message.entryId);
        }
if ( message.operation !== "") {
          writer.uint32(26).string(message.operation);
        }
if ( message.performedBy !== "") {
          writer.uint32(34).string(message.performedBy);
        }
if ( message.timestamp !== "0") {
          writer.uint32(40).int64(message.timestamp);
        }
if (message.oldValue !== undefined ) {
          writer.uint32(50).string(message.oldValue);
        }
if (message.newValue !== undefined ) {
          writer.uint32(58).string(message.newValue);
        }
return writer;
},

decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): MemoryAuditLog {
      const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
const message = createBaseMemoryAuditLog();
while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
case 1: {
if (tag !== 8) {
        break;
      }
    
        message.id = reader.int64().toString();
continue; }
case 2: {
if (tag !== 16) {
        break;
      }
    
        message.entryId = reader.int64().toString();
continue; }
case 3: {
if (tag !== 26) {
        break;
      }
    
        message.operation = reader.string();
continue; }
case 4: {
if (tag !== 34) {
        break;
      }
    
        message.performedBy = reader.string();
continue; }
case 5: {
if (tag !== 40) {
        break;
      }
    
        message.timestamp = reader.int64().toString();
continue; }
case 6: {
if (tag !== 50) {
        break;
      }
    
        message.oldValue = reader.string();
continue; }
case 7: {
if (tag !== 58) {
        break;
      }
    
        message.newValue = reader.string();
continue; }
}
if ((tag & 7) === 4 || tag === 0) {
        break;
      }
reader.skip(tag & 7);
}
return message;
},

fromJSON(object: any): MemoryAuditLog {
      return {
id: isSet(object.id) ? globalThis.String(object.id)
        
          : "0",
entryId: isSet(object.entryId) ? globalThis.String(object.entryId)
         : isSet(object.entry_id) ? globalThis.String(object.entry_id)
          : "0",
operation: isSet(object.operation) ? globalThis.String(object.operation)
        
          : "",
performedBy: isSet(object.performedBy) ? globalThis.String(object.performedBy)
         : isSet(object.performed_by) ? globalThis.String(object.performed_by)
          : "",
timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp)
        
          : "0",
oldValue: isSet(object.oldValue) ? globalThis.String(object.oldValue)
         : isSet(object.old_value) ? globalThis.String(object.old_value)
          : undefined,
newValue: isSet(object.newValue) ? globalThis.String(object.newValue)
         : isSet(object.new_value) ? globalThis.String(object.new_value)
          : undefined,
};
},

toJSON(message: MemoryAuditLog): unknown {
      const obj: any = {};
if ( message.id !== "0") {
          obj.id = message.id;
        }
if ( message.entryId !== "0") {
          obj.entryId = message.entryId;
        }
if ( message.operation !== "") {
          obj.operation = message.operation;
        }
if ( message.performedBy !== "") {
          obj.performedBy = message.performedBy;
        }
if ( message.timestamp !== "0") {
          obj.timestamp = message.timestamp;
        }
if (message.oldValue !== undefined ) {
          obj.oldValue = message.oldValue;
        }
if (message.newValue !== undefined ) {
          obj.newValue = message.newValue;
        }
return obj;
},

create<I extends Exact<DeepPartial<MemoryAuditLog>, I>>(base?: I): MemoryAuditLog {
        return MemoryAuditLog.fromPartial(base ?? ({} as any));
      },
fromPartial<I extends Exact<DeepPartial<MemoryAuditLog>, I>>(object: I): MemoryAuditLog {
const message = createBaseMemoryAuditLog();
message.id = object.id ?? "0";
message.entryId = object.entryId ?? "0";
message.operation = object.operation ?? "";
message.performedBy = object.performedBy ?? "";
message.timestamp = object.timestamp ?? "0";
message.oldValue = object.oldValue ?? undefined;
message.newValue = object.newValue ?? undefined;
return message;
}
            };

function createBasePromptBlock(): PromptBlock {
      return { id: "",type: 0,priority: 0,scope: 0,content: "",source: "",constraints: undefined,dependencies: [],version: 0 };
    }

export const PromptBlock: MessageFns<PromptBlock> = {
              encode(
      message: PromptBlock,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
if ( message.id !== "") {
          writer.uint32(10).string(message.id);
        }
if ( message.type !== 0) {
          writer.uint32(16).int32(message.type);
        }
if ( message.priority !== 0) {
          writer.uint32(24).int32(message.priority);
        }
if ( message.scope !== 0) {
          writer.uint32(32).int32(message.scope);
        }
if ( message.content !== "") {
          writer.uint32(42).string(message.content);
        }
if ( message.source !== "") {
          writer.uint32(50).string(message.source);
        }
if (message.constraints !== undefined ) {
          writer.uint32(58).string(message.constraints);
        }
for (const v of message.dependencies) {
            writer.uint32(66).string(v!);
          }
if ( message.version !== 0) {
          writer.uint32(72).int32(message.version);
        }
return writer;
},

decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): PromptBlock {
      const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
const message = createBasePromptBlock();
while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
case 1: {
if (tag !== 10) {
        break;
      }
    
        message.id = reader.string();
continue; }
case 2: {
if (tag !== 16) {
        break;
      }
    
        message.type = reader.int32() as any;
continue; }
case 3: {
if (tag !== 24) {
        break;
      }
    
        message.priority = reader.int32();
continue; }
case 4: {
if (tag !== 32) {
        break;
      }
    
        message.scope = reader.int32() as any;
continue; }
case 5: {
if (tag !== 42) {
        break;
      }
    
        message.content = reader.string();
continue; }
case 6: {
if (tag !== 50) {
        break;
      }
    
        message.source = reader.string();
continue; }
case 7: {
if (tag !== 58) {
        break;
      }
    
        message.constraints = reader.string();
continue; }
case 8: {
if (tag !== 66) {
        break;
      }
    
              
              message.dependencies.push(reader.string());
continue; }
case 9: {
if (tag !== 72) {
        break;
      }
    
        message.version = reader.int32();
continue; }
}
if ((tag & 7) === 4 || tag === 0) {
        break;
      }
reader.skip(tag & 7);
}
return message;
},

fromJSON(object: any): PromptBlock {
      return {
id: isSet(object.id) ? globalThis.String(object.id)
        
          : "",
type: isSet(object.type) ? promptBlockTypeFromJSON(object.type)
        
          : 0,
priority: isSet(object.priority) ? globalThis.Number(object.priority)
        
          : 0,
scope: isSet(object.scope) ? memoryScopeFromJSON(object.scope)
        
          : 0,
content: isSet(object.content) ? globalThis.String(object.content)
        
          : "",
source: isSet(object.source) ? globalThis.String(object.source)
        
          : "",
constraints: isSet(object.constraints) ? globalThis.String(object.constraints)
        
          : undefined,
dependencies: globalThis.Array.isArray(object?.dependencies) ? object.dependencies.map((e: any) => globalThis.String(e))  : [],
version: isSet(object.version) ? globalThis.Number(object.version)
        
          : 0,
};
},

toJSON(message: PromptBlock): unknown {
      const obj: any = {};
if ( message.id !== "") {
          obj.id = message.id;
        }
if ( message.type !== 0) {
          obj.type = promptBlockTypeToJSON(message.type);
        }
if ( message.priority !== 0) {
          obj.priority = Math.round(message.priority);
        }
if ( message.scope !== 0) {
          obj.scope = memoryScopeToJSON(message.scope);
        }
if ( message.content !== "") {
          obj.content = message.content;
        }
if ( message.source !== "") {
          obj.source = message.source;
        }
if (message.constraints !== undefined ) {
          obj.constraints = message.constraints;
        }
if (message.dependencies?.length) {
          obj.dependencies = message.dependencies;
        }
if ( message.version !== 0) {
          obj.version = Math.round(message.version);
        }
return obj;
},

create<I extends Exact<DeepPartial<PromptBlock>, I>>(base?: I): PromptBlock {
        return PromptBlock.fromPartial(base ?? ({} as any));
      },
fromPartial<I extends Exact<DeepPartial<PromptBlock>, I>>(object: I): PromptBlock {
const message = createBasePromptBlock();
message.id = object.id ?? "";
message.type = object.type ?? 0;
message.priority = object.priority ?? 0;
message.scope = object.scope ?? 0;
message.content = object.content ?? "";
message.source = object.source ?? "";
message.constraints = object.constraints ?? undefined;
message.dependencies = object.dependencies?.map((e) => e) || [];
message.version = object.version ?? 0;
return message;
}
            };

function createBaseContextPack(): ContextPack {
      return { sessionId: "",blocks: [],assembledAt: "0",traceId: undefined,totalTokensEstimate: 0 };
    }

export const ContextPack: MessageFns<ContextPack> = {
              encode(
      message: ContextPack,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
if ( message.sessionId !== "") {
          writer.uint32(10).string(message.sessionId);
        }
for (const v of message.blocks) {
            PromptBlock.encode(v!, writer.uint32(18).fork()).join();
          }
if ( message.assembledAt !== "0") {
          writer.uint32(24).int64(message.assembledAt);
        }
if (message.traceId !== undefined ) {
          writer.uint32(34).string(message.traceId);
        }
if ( message.totalTokensEstimate !== 0) {
          writer.uint32(40).int32(message.totalTokensEstimate);
        }
return writer;
},

decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): ContextPack {
      const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
const message = createBaseContextPack();
while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
case 1: {
if (tag !== 10) {
        break;
      }
    
        message.sessionId = reader.string();
continue; }
case 2: {
if (tag !== 18) {
        break;
      }
    
              
              message.blocks.push(PromptBlock.decode(reader, reader.uint32()));
continue; }
case 3: {
if (tag !== 24) {
        break;
      }
    
        message.assembledAt = reader.int64().toString();
continue; }
case 4: {
if (tag !== 34) {
        break;
      }
    
        message.traceId = reader.string();
continue; }
case 5: {
if (tag !== 40) {
        break;
      }
    
        message.totalTokensEstimate = reader.int32();
continue; }
}
if ((tag & 7) === 4 || tag === 0) {
        break;
      }
reader.skip(tag & 7);
}
return message;
},

fromJSON(object: any): ContextPack {
      return {
sessionId: isSet(object.sessionId) ? globalThis.String(object.sessionId)
         : isSet(object.session_id) ? globalThis.String(object.session_id)
          : "",
blocks: globalThis.Array.isArray(object?.blocks) ? object.blocks.map((e: any) => PromptBlock.fromJSON(e))  : [],
assembledAt: isSet(object.assembledAt) ? globalThis.String(object.assembledAt)
         : isSet(object.assembled_at) ? globalThis.String(object.assembled_at)
          : "0",
traceId: isSet(object.traceId) ? globalThis.String(object.traceId)
         : isSet(object.trace_id) ? globalThis.String(object.trace_id)
          : undefined,
totalTokensEstimate: isSet(object.totalTokensEstimate) ? globalThis.Number(object.totalTokensEstimate)
         : isSet(object.total_tokens_estimate) ? globalThis.Number(object.total_tokens_estimate)
          : 0,
};
},

toJSON(message: ContextPack): unknown {
      const obj: any = {};
if ( message.sessionId !== "") {
          obj.sessionId = message.sessionId;
        }
if (message.blocks?.length) {
          obj.blocks = message.blocks.map(e => PromptBlock.toJSON(e));
        }
if ( message.assembledAt !== "0") {
          obj.assembledAt = message.assembledAt;
        }
if (message.traceId !== undefined ) {
          obj.traceId = message.traceId;
        }
if ( message.totalTokensEstimate !== 0) {
          obj.totalTokensEstimate = Math.round(message.totalTokensEstimate);
        }
return obj;
},

create<I extends Exact<DeepPartial<ContextPack>, I>>(base?: I): ContextPack {
        return ContextPack.fromPartial(base ?? ({} as any));
      },
fromPartial<I extends Exact<DeepPartial<ContextPack>, I>>(object: I): ContextPack {
const message = createBaseContextPack();
message.sessionId = object.sessionId ?? "";
message.blocks = object.blocks?.map((e) => PromptBlock.fromPartial(e)) || [];
message.assembledAt = object.assembledAt ?? "0";
message.traceId = object.traceId ?? undefined;
message.totalTokensEstimate = object.totalTokensEstimate ?? 0;
return message;
}
            };

function createBaseConflictRecord(): ConflictRecord {
      return { id: "",conflictingBlockIds: "",conflictType: "",description: "",resolution: "",resolvedBy: "",resolvedAt: "0",isResolved: false };
    }

export const ConflictRecord: MessageFns<ConflictRecord> = {
              encode(
      message: ConflictRecord,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
if ( message.id !== "") {
          writer.uint32(10).string(message.id);
        }
if ( message.conflictingBlockIds !== "") {
          writer.uint32(18).string(message.conflictingBlockIds);
        }
if ( message.conflictType !== "") {
          writer.uint32(26).string(message.conflictType);
        }
if ( message.description !== "") {
          writer.uint32(34).string(message.description);
        }
if ( message.resolution !== "") {
          writer.uint32(42).string(message.resolution);
        }
if ( message.resolvedBy !== "") {
          writer.uint32(50).string(message.resolvedBy);
        }
if ( message.resolvedAt !== "0") {
          writer.uint32(56).int64(message.resolvedAt);
        }
if ( message.isResolved !== false) {
          writer.uint32(64).bool(message.isResolved);
        }
return writer;
},

decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): ConflictRecord {
      const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
const message = createBaseConflictRecord();
while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
case 1: {
if (tag !== 10) {
        break;
      }
    
        message.id = reader.string();
continue; }
case 2: {
if (tag !== 18) {
        break;
      }
    
        message.conflictingBlockIds = reader.string();
continue; }
case 3: {
if (tag !== 26) {
        break;
      }
    
        message.conflictType = reader.string();
continue; }
case 4: {
if (tag !== 34) {
        break;
      }
    
        message.description = reader.string();
continue; }
case 5: {
if (tag !== 42) {
        break;
      }
    
        message.resolution = reader.string();
continue; }
case 6: {
if (tag !== 50) {
        break;
      }
    
        message.resolvedBy = reader.string();
continue; }
case 7: {
if (tag !== 56) {
        break;
      }
    
        message.resolvedAt = reader.int64().toString();
continue; }
case 8: {
if (tag !== 64) {
        break;
      }
    
        message.isResolved = reader.bool();
continue; }
}
if ((tag & 7) === 4 || tag === 0) {
        break;
      }
reader.skip(tag & 7);
}
return message;
},

fromJSON(object: any): ConflictRecord {
      return {
id: isSet(object.id) ? globalThis.String(object.id)
        
          : "",
conflictingBlockIds: isSet(object.conflictingBlockIds) ? globalThis.String(object.conflictingBlockIds)
         : isSet(object.conflicting_block_ids) ? globalThis.String(object.conflicting_block_ids)
          : "",
conflictType: isSet(object.conflictType) ? globalThis.String(object.conflictType)
         : isSet(object.conflict_type) ? globalThis.String(object.conflict_type)
          : "",
description: isSet(object.description) ? globalThis.String(object.description)
        
          : "",
resolution: isSet(object.resolution) ? globalThis.String(object.resolution)
        
          : "",
resolvedBy: isSet(object.resolvedBy) ? globalThis.String(object.resolvedBy)
         : isSet(object.resolved_by) ? globalThis.String(object.resolved_by)
          : "",
resolvedAt: isSet(object.resolvedAt) ? globalThis.String(object.resolvedAt)
         : isSet(object.resolved_at) ? globalThis.String(object.resolved_at)
          : "0",
isResolved: isSet(object.isResolved) ? globalThis.Boolean(object.isResolved)
         : isSet(object.is_resolved) ? globalThis.Boolean(object.is_resolved)
          : false,
};
},

toJSON(message: ConflictRecord): unknown {
      const obj: any = {};
if ( message.id !== "") {
          obj.id = message.id;
        }
if ( message.conflictingBlockIds !== "") {
          obj.conflictingBlockIds = message.conflictingBlockIds;
        }
if ( message.conflictType !== "") {
          obj.conflictType = message.conflictType;
        }
if ( message.description !== "") {
          obj.description = message.description;
        }
if ( message.resolution !== "") {
          obj.resolution = message.resolution;
        }
if ( message.resolvedBy !== "") {
          obj.resolvedBy = message.resolvedBy;
        }
if ( message.resolvedAt !== "0") {
          obj.resolvedAt = message.resolvedAt;
        }
if ( message.isResolved !== false) {
          obj.isResolved = message.isResolved;
        }
return obj;
},

create<I extends Exact<DeepPartial<ConflictRecord>, I>>(base?: I): ConflictRecord {
        return ConflictRecord.fromPartial(base ?? ({} as any));
      },
fromPartial<I extends Exact<DeepPartial<ConflictRecord>, I>>(object: I): ConflictRecord {
const message = createBaseConflictRecord();
message.id = object.id ?? "";
message.conflictingBlockIds = object.conflictingBlockIds ?? "";
message.conflictType = object.conflictType ?? "";
message.description = object.description ?? "";
message.resolution = object.resolution ?? "";
message.resolvedBy = object.resolvedBy ?? "";
message.resolvedAt = object.resolvedAt ?? "0";
message.isResolved = object.isResolved ?? false;
return message;
}
            };

function createBasePolicyRule(): PolicyRule {
      return { id: "",ruleType: "",name: "",description: "",condition: "",action: "",priority: 0,scope: "",enabled: false,effectiveFrom: "0",effectiveUntil: undefined };
    }

export const PolicyRule: MessageFns<PolicyRule> = {
              encode(
      message: PolicyRule,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
if ( message.id !== "") {
          writer.uint32(10).string(message.id);
        }
if ( message.ruleType !== "") {
          writer.uint32(18).string(message.ruleType);
        }
if ( message.name !== "") {
          writer.uint32(26).string(message.name);
        }
if ( message.description !== "") {
          writer.uint32(34).string(message.description);
        }
if ( message.condition !== "") {
          writer.uint32(42).string(message.condition);
        }
if ( message.action !== "") {
          writer.uint32(50).string(message.action);
        }
if ( message.priority !== 0) {
          writer.uint32(56).int32(message.priority);
        }
if ( message.scope !== "") {
          writer.uint32(66).string(message.scope);
        }
if ( message.enabled !== false) {
          writer.uint32(72).bool(message.enabled);
        }
if ( message.effectiveFrom !== "0") {
          writer.uint32(80).int64(message.effectiveFrom);
        }
if (message.effectiveUntil !== undefined ) {
          writer.uint32(88).int64(message.effectiveUntil);
        }
return writer;
},

decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): PolicyRule {
      const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
const message = createBasePolicyRule();
while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
case 1: {
if (tag !== 10) {
        break;
      }
    
        message.id = reader.string();
continue; }
case 2: {
if (tag !== 18) {
        break;
      }
    
        message.ruleType = reader.string();
continue; }
case 3: {
if (tag !== 26) {
        break;
      }
    
        message.name = reader.string();
continue; }
case 4: {
if (tag !== 34) {
        break;
      }
    
        message.description = reader.string();
continue; }
case 5: {
if (tag !== 42) {
        break;
      }
    
        message.condition = reader.string();
continue; }
case 6: {
if (tag !== 50) {
        break;
      }
    
        message.action = reader.string();
continue; }
case 7: {
if (tag !== 56) {
        break;
      }
    
        message.priority = reader.int32();
continue; }
case 8: {
if (tag !== 66) {
        break;
      }
    
        message.scope = reader.string();
continue; }
case 9: {
if (tag !== 72) {
        break;
      }
    
        message.enabled = reader.bool();
continue; }
case 10: {
if (tag !== 80) {
        break;
      }
    
        message.effectiveFrom = reader.int64().toString();
continue; }
case 11: {
if (tag !== 88) {
        break;
      }
    
        message.effectiveUntil = reader.int64().toString();
continue; }
}
if ((tag & 7) === 4 || tag === 0) {
        break;
      }
reader.skip(tag & 7);
}
return message;
},

fromJSON(object: any): PolicyRule {
      return {
id: isSet(object.id) ? globalThis.String(object.id)
        
          : "",
ruleType: isSet(object.ruleType) ? globalThis.String(object.ruleType)
         : isSet(object.rule_type) ? globalThis.String(object.rule_type)
          : "",
name: isSet(object.name) ? globalThis.String(object.name)
        
          : "",
description: isSet(object.description) ? globalThis.String(object.description)
        
          : "",
condition: isSet(object.condition) ? globalThis.String(object.condition)
        
          : "",
action: isSet(object.action) ? globalThis.String(object.action)
        
          : "",
priority: isSet(object.priority) ? globalThis.Number(object.priority)
        
          : 0,
scope: isSet(object.scope) ? globalThis.String(object.scope)
        
          : "",
enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled)
        
          : false,
effectiveFrom: isSet(object.effectiveFrom) ? globalThis.String(object.effectiveFrom)
         : isSet(object.effective_from) ? globalThis.String(object.effective_from)
          : "0",
effectiveUntil: isSet(object.effectiveUntil) ? globalThis.String(object.effectiveUntil)
         : isSet(object.effective_until) ? globalThis.String(object.effective_until)
          : undefined,
};
},

toJSON(message: PolicyRule): unknown {
      const obj: any = {};
if ( message.id !== "") {
          obj.id = message.id;
        }
if ( message.ruleType !== "") {
          obj.ruleType = message.ruleType;
        }
if ( message.name !== "") {
          obj.name = message.name;
        }
if ( message.description !== "") {
          obj.description = message.description;
        }
if ( message.condition !== "") {
          obj.condition = message.condition;
        }
if ( message.action !== "") {
          obj.action = message.action;
        }
if ( message.priority !== 0) {
          obj.priority = Math.round(message.priority);
        }
if ( message.scope !== "") {
          obj.scope = message.scope;
        }
if ( message.enabled !== false) {
          obj.enabled = message.enabled;
        }
if ( message.effectiveFrom !== "0") {
          obj.effectiveFrom = message.effectiveFrom;
        }
if (message.effectiveUntil !== undefined ) {
          obj.effectiveUntil = message.effectiveUntil;
        }
return obj;
},

create<I extends Exact<DeepPartial<PolicyRule>, I>>(base?: I): PolicyRule {
        return PolicyRule.fromPartial(base ?? ({} as any));
      },
fromPartial<I extends Exact<DeepPartial<PolicyRule>, I>>(object: I): PolicyRule {
const message = createBasePolicyRule();
message.id = object.id ?? "";
message.ruleType = object.ruleType ?? "";
message.name = object.name ?? "";
message.description = object.description ?? "";
message.condition = object.condition ?? "";
message.action = object.action ?? "";
message.priority = object.priority ?? 0;
message.scope = object.scope ?? "";
message.enabled = object.enabled ?? false;
message.effectiveFrom = object.effectiveFrom ?? "0";
message.effectiveUntil = object.effectiveUntil ?? undefined;
return message;
}
            };

function createBasePolicyEvaluation(): PolicyEvaluation {
      return { contextId: "",ruleId: "",allowed: false,modification: "",reason: "" };
    }

export const PolicyEvaluation: MessageFns<PolicyEvaluation> = {
              encode(
      message: PolicyEvaluation,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
if ( message.contextId !== "") {
          writer.uint32(10).string(message.contextId);
        }
if ( message.ruleId !== "") {
          writer.uint32(18).string(message.ruleId);
        }
if ( message.allowed !== false) {
          writer.uint32(24).bool(message.allowed);
        }
if ( message.modification !== "") {
          writer.uint32(34).string(message.modification);
        }
if ( message.reason !== "") {
          writer.uint32(42).string(message.reason);
        }
return writer;
},

decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): PolicyEvaluation {
      const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
const message = createBasePolicyEvaluation();
while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
case 1: {
if (tag !== 10) {
        break;
      }
    
        message.contextId = reader.string();
continue; }
case 2: {
if (tag !== 18) {
        break;
      }
    
        message.ruleId = reader.string();
continue; }
case 3: {
if (tag !== 24) {
        break;
      }
    
        message.allowed = reader.bool();
continue; }
case 4: {
if (tag !== 34) {
        break;
      }
    
        message.modification = reader.string();
continue; }
case 5: {
if (tag !== 42) {
        break;
      }
    
        message.reason = reader.string();
continue; }
}
if ((tag & 7) === 4 || tag === 0) {
        break;
      }
reader.skip(tag & 7);
}
return message;
},

fromJSON(object: any): PolicyEvaluation {
      return {
contextId: isSet(object.contextId) ? globalThis.String(object.contextId)
         : isSet(object.context_id) ? globalThis.String(object.context_id)
          : "",
ruleId: isSet(object.ruleId) ? globalThis.String(object.ruleId)
         : isSet(object.rule_id) ? globalThis.String(object.rule_id)
          : "",
allowed: isSet(object.allowed) ? globalThis.Boolean(object.allowed)
        
          : false,
modification: isSet(object.modification) ? globalThis.String(object.modification)
        
          : "",
reason: isSet(object.reason) ? globalThis.String(object.reason)
        
          : "",
};
},

toJSON(message: PolicyEvaluation): unknown {
      const obj: any = {};
if ( message.contextId !== "") {
          obj.contextId = message.contextId;
        }
if ( message.ruleId !== "") {
          obj.ruleId = message.ruleId;
        }
if ( message.allowed !== false) {
          obj.allowed = message.allowed;
        }
if ( message.modification !== "") {
          obj.modification = message.modification;
        }
if ( message.reason !== "") {
          obj.reason = message.reason;
        }
return obj;
},

create<I extends Exact<DeepPartial<PolicyEvaluation>, I>>(base?: I): PolicyEvaluation {
        return PolicyEvaluation.fromPartial(base ?? ({} as any));
      },
fromPartial<I extends Exact<DeepPartial<PolicyEvaluation>, I>>(object: I): PolicyEvaluation {
const message = createBasePolicyEvaluation();
message.contextId = object.contextId ?? "";
message.ruleId = object.ruleId ?? "";
message.allowed = object.allowed ?? false;
message.modification = object.modification ?? "";
message.reason = object.reason ?? "";
return message;
}
            };

function createBaseTestCase(): TestCase {
      return { id: "",type: "",title: "",description: "",precondition: "",steps: "",expectedResult: "",relatedStepId: "",estimatedDuration: 0 };
    }

export const TestCase: MessageFns<TestCase> = {
              encode(
      message: TestCase,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
if ( message.id !== "") {
          writer.uint32(10).string(message.id);
        }
if ( message.type !== "") {
          writer.uint32(18).string(message.type);
        }
if ( message.title !== "") {
          writer.uint32(26).string(message.title);
        }
if ( message.description !== "") {
          writer.uint32(34).string(message.description);
        }
if ( message.precondition !== "") {
          writer.uint32(42).string(message.precondition);
        }
if ( message.steps !== "") {
          writer.uint32(50).string(message.steps);
        }
if ( message.expectedResult !== "") {
          writer.uint32(58).string(message.expectedResult);
        }
if ( message.relatedStepId !== "") {
          writer.uint32(66).string(message.relatedStepId);
        }
if ( message.estimatedDuration !== 0) {
          writer.uint32(77).float(message.estimatedDuration);
        }
return writer;
},

decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): TestCase {
      const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
const message = createBaseTestCase();
while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
case 1: {
if (tag !== 10) {
        break;
      }
    
        message.id = reader.string();
continue; }
case 2: {
if (tag !== 18) {
        break;
      }
    
        message.type = reader.string();
continue; }
case 3: {
if (tag !== 26) {
        break;
      }
    
        message.title = reader.string();
continue; }
case 4: {
if (tag !== 34) {
        break;
      }
    
        message.description = reader.string();
continue; }
case 5: {
if (tag !== 42) {
        break;
      }
    
        message.precondition = reader.string();
continue; }
case 6: {
if (tag !== 50) {
        break;
      }
    
        message.steps = reader.string();
continue; }
case 7: {
if (tag !== 58) {
        break;
      }
    
        message.expectedResult = reader.string();
continue; }
case 8: {
if (tag !== 66) {
        break;
      }
    
        message.relatedStepId = reader.string();
continue; }
case 9: {
if (tag !== 77) {
        break;
      }
    
        message.estimatedDuration = reader.float();
continue; }
}
if ((tag & 7) === 4 || tag === 0) {
        break;
      }
reader.skip(tag & 7);
}
return message;
},

fromJSON(object: any): TestCase {
      return {
id: isSet(object.id) ? globalThis.String(object.id)
        
          : "",
type: isSet(object.type) ? globalThis.String(object.type)
        
          : "",
title: isSet(object.title) ? globalThis.String(object.title)
        
          : "",
description: isSet(object.description) ? globalThis.String(object.description)
        
          : "",
precondition: isSet(object.precondition) ? globalThis.String(object.precondition)
        
          : "",
steps: isSet(object.steps) ? globalThis.String(object.steps)
        
          : "",
expectedResult: isSet(object.expectedResult) ? globalThis.String(object.expectedResult)
         : isSet(object.expected_result) ? globalThis.String(object.expected_result)
          : "",
relatedStepId: isSet(object.relatedStepId) ? globalThis.String(object.relatedStepId)
         : isSet(object.related_step_id) ? globalThis.String(object.related_step_id)
          : "",
estimatedDuration: isSet(object.estimatedDuration) ? globalThis.Number(object.estimatedDuration)
         : isSet(object.estimated_duration) ? globalThis.Number(object.estimated_duration)
          : 0,
};
},

toJSON(message: TestCase): unknown {
      const obj: any = {};
if ( message.id !== "") {
          obj.id = message.id;
        }
if ( message.type !== "") {
          obj.type = message.type;
        }
if ( message.title !== "") {
          obj.title = message.title;
        }
if ( message.description !== "") {
          obj.description = message.description;
        }
if ( message.precondition !== "") {
          obj.precondition = message.precondition;
        }
if ( message.steps !== "") {
          obj.steps = message.steps;
        }
if ( message.expectedResult !== "") {
          obj.expectedResult = message.expectedResult;
        }
if ( message.relatedStepId !== "") {
          obj.relatedStepId = message.relatedStepId;
        }
if ( message.estimatedDuration !== 0) {
          obj.estimatedDuration = message.estimatedDuration;
        }
return obj;
},

create<I extends Exact<DeepPartial<TestCase>, I>>(base?: I): TestCase {
        return TestCase.fromPartial(base ?? ({} as any));
      },
fromPartial<I extends Exact<DeepPartial<TestCase>, I>>(object: I): TestCase {
const message = createBaseTestCase();
message.id = object.id ?? "";
message.type = object.type ?? "";
message.title = object.title ?? "";
message.description = object.description ?? "";
message.precondition = object.precondition ?? "";
message.steps = object.steps ?? "";
message.expectedResult = object.expectedResult ?? "";
message.relatedStepId = object.relatedStepId ?? "";
message.estimatedDuration = object.estimatedDuration ?? 0;
return message;
}
            };

function createBaseTestSuite(): TestSuite {
      return { id: "",name: "",testCaseIds: [] };
    }

export const TestSuite: MessageFns<TestSuite> = {
              encode(
      message: TestSuite,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
if ( message.id !== "") {
          writer.uint32(10).string(message.id);
        }
if ( message.name !== "") {
          writer.uint32(18).string(message.name);
        }
for (const v of message.testCaseIds) {
            writer.uint32(26).string(v!);
          }
return writer;
},

decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): TestSuite {
      const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
const message = createBaseTestSuite();
while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
case 1: {
if (tag !== 10) {
        break;
      }
    
        message.id = reader.string();
continue; }
case 2: {
if (tag !== 18) {
        break;
      }
    
        message.name = reader.string();
continue; }
case 3: {
if (tag !== 26) {
        break;
      }
    
              
              message.testCaseIds.push(reader.string());
continue; }
}
if ((tag & 7) === 4 || tag === 0) {
        break;
      }
reader.skip(tag & 7);
}
return message;
},

fromJSON(object: any): TestSuite {
      return {
id: isSet(object.id) ? globalThis.String(object.id)
        
          : "",
name: isSet(object.name) ? globalThis.String(object.name)
        
          : "",
testCaseIds: globalThis.Array.isArray(object?.testCaseIds) ? object.testCaseIds.map((e: any) => globalThis.String(e))  : globalThis.Array.isArray(object?.test_case_ids) ? object.test_case_ids.map((e: any) => globalThis.String(e)) : [],
};
},

toJSON(message: TestSuite): unknown {
      const obj: any = {};
if ( message.id !== "") {
          obj.id = message.id;
        }
if ( message.name !== "") {
          obj.name = message.name;
        }
if (message.testCaseIds?.length) {
          obj.testCaseIds = message.testCaseIds;
        }
return obj;
},

create<I extends Exact<DeepPartial<TestSuite>, I>>(base?: I): TestSuite {
        return TestSuite.fromPartial(base ?? ({} as any));
      },
fromPartial<I extends Exact<DeepPartial<TestSuite>, I>>(object: I): TestSuite {
const message = createBaseTestSuite();
message.id = object.id ?? "";
message.name = object.name ?? "";
message.testCaseIds = object.testCaseIds?.map((e) => e) || [];
return message;
}
            };

function createBaseTestPlan(): TestPlan {
      return { id: "",templateId: "",version: "",suites: [],testCases: {},coverageTarget: 0,generatedBy: "",generatedAt: "0",llmModelUsed: undefined };
    }

export const TestPlan: MessageFns<TestPlan> = {
              encode(
      message: TestPlan,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
if ( message.id !== "") {
          writer.uint32(10).string(message.id);
        }
if ( message.templateId !== "") {
          writer.uint32(18).string(message.templateId);
        }
if ( message.version !== "") {
          writer.uint32(26).string(message.version);
        }
for (const v of message.suites) {
            TestSuite.encode(v!, writer.uint32(34).fork()).join();
          }
globalThis.Object.entries(message.testCases).forEach(([key, value]: [string, TestCase]) => {
              TestPlan_TestCasesEntry.encode({  key: key as any, value }, writer.uint32(42).fork()).join()
            });
if ( message.coverageTarget !== 0) {
          writer.uint32(53).float(message.coverageTarget);
        }
if ( message.generatedBy !== "") {
          writer.uint32(58).string(message.generatedBy);
        }
if ( message.generatedAt !== "0") {
          writer.uint32(64).int64(message.generatedAt);
        }
if (message.llmModelUsed !== undefined ) {
          writer.uint32(74).string(message.llmModelUsed);
        }
return writer;
},

decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): TestPlan {
      const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
const message = createBaseTestPlan();
while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
case 1: {
if (tag !== 10) {
        break;
      }
    
        message.id = reader.string();
continue; }
case 2: {
if (tag !== 18) {
        break;
      }
    
        message.templateId = reader.string();
continue; }
case 3: {
if (tag !== 26) {
        break;
      }
    
        message.version = reader.string();
continue; }
case 4: {
if (tag !== 34) {
        break;
      }
    
              
              message.suites.push(TestSuite.decode(reader, reader.uint32()));
continue; }
case 5: {
if (tag !== 42) {
        break;
      }
    
          const entry5 = TestPlan_TestCasesEntry.decode(reader, reader.uint32());
          if (entry5.value !== undefined ) {
            
            message.testCases[entry5.key] = entry5.value;
          }
continue; }
case 6: {
if (tag !== 53) {
        break;
      }
    
        message.coverageTarget = reader.float();
continue; }
case 7: {
if (tag !== 58) {
        break;
      }
    
        message.generatedBy = reader.string();
continue; }
case 8: {
if (tag !== 64) {
        break;
      }
    
        message.generatedAt = reader.int64().toString();
continue; }
case 9: {
if (tag !== 74) {
        break;
      }
    
        message.llmModelUsed = reader.string();
continue; }
}
if ((tag & 7) === 4 || tag === 0) {
        break;
      }
reader.skip(tag & 7);
}
return message;
},

fromJSON(object: any): TestPlan {
      return {
id: isSet(object.id) ? globalThis.String(object.id)
        
          : "",
templateId: isSet(object.templateId) ? globalThis.String(object.templateId)
         : isSet(object.template_id) ? globalThis.String(object.template_id)
          : "",
version: isSet(object.version) ? globalThis.String(object.version)
        
          : "",
suites: globalThis.Array.isArray(object?.suites) ? object.suites.map((e: any) => TestSuite.fromJSON(e))  : [],
testCases: isObject(object.testCases)
              ? (globalThis.Object.entries(object.testCases) as [string, any][]).reduce((acc: { [key: string ]: TestCase }, [key, value]: [string, any]) => {
                  acc[key] = TestCase.fromJSON(value);
                  return acc;
                }, {})
              
                 : isObject(object.test_cases)
                 ? (globalThis.Object.entries(object.test_cases) as [string, any][]).reduce((acc: { [key: string ]: TestCase }, [key, value]: [string, any]) => {
                     acc[key] = TestCase.fromJSON(value);
                     return acc;
                   }, {})
               
              : {},
coverageTarget: isSet(object.coverageTarget) ? globalThis.Number(object.coverageTarget)
         : isSet(object.coverage_target) ? globalThis.Number(object.coverage_target)
          : 0,
generatedBy: isSet(object.generatedBy) ? globalThis.String(object.generatedBy)
         : isSet(object.generated_by) ? globalThis.String(object.generated_by)
          : "",
generatedAt: isSet(object.generatedAt) ? globalThis.String(object.generatedAt)
         : isSet(object.generated_at) ? globalThis.String(object.generated_at)
          : "0",
llmModelUsed: isSet(object.llmModelUsed) ? globalThis.String(object.llmModelUsed)
         : isSet(object.llm_model_used) ? globalThis.String(object.llm_model_used)
          : undefined,
};
},

toJSON(message: TestPlan): unknown {
      const obj: any = {};
if ( message.id !== "") {
          obj.id = message.id;
        }
if ( message.templateId !== "") {
          obj.templateId = message.templateId;
        }
if ( message.version !== "") {
          obj.version = message.version;
        }
if (message.suites?.length) {
          obj.suites = message.suites.map(e => TestSuite.toJSON(e));
        }
if (message.testCases) {
            const entries = globalThis.Object.entries(message.testCases) as [string, TestCase][];
            if (entries.length > 0) {
              obj.testCases = {};
              entries.forEach(([k, v]) => {
                obj.testCases[k] = TestCase.toJSON(v);
              });
            }
          }
if ( message.coverageTarget !== 0) {
          obj.coverageTarget = message.coverageTarget;
        }
if ( message.generatedBy !== "") {
          obj.generatedBy = message.generatedBy;
        }
if ( message.generatedAt !== "0") {
          obj.generatedAt = message.generatedAt;
        }
if (message.llmModelUsed !== undefined ) {
          obj.llmModelUsed = message.llmModelUsed;
        }
return obj;
},

create<I extends Exact<DeepPartial<TestPlan>, I>>(base?: I): TestPlan {
        return TestPlan.fromPartial(base ?? ({} as any));
      },
fromPartial<I extends Exact<DeepPartial<TestPlan>, I>>(object: I): TestPlan {
const message = createBaseTestPlan();
message.id = object.id ?? "";
message.templateId = object.templateId ?? "";
message.version = object.version ?? "";
message.suites = object.suites?.map((e) => TestSuite.fromPartial(e)) || [];
message.testCases =  (globalThis.Object.entries(object.testCases ?? {}) as [string, TestCase][]).reduce(
              (acc: { [key: string ]: TestCase }, [key, value]: [string, TestCase]) => {
                if (value !== undefined) {
                  acc[key] = TestCase.fromPartial(value);
                }
                return acc;
              },
              {},
            );
message.coverageTarget = object.coverageTarget ?? 0;
message.generatedBy = object.generatedBy ?? "";
message.generatedAt = object.generatedAt ?? "0";
message.llmModelUsed = object.llmModelUsed ?? undefined;
return message;
}
            };

function createBaseTestPlan_TestCasesEntry(): TestPlan_TestCasesEntry {
      return { key: "",value: undefined };
    }

export const TestPlan_TestCasesEntry: MessageFns<TestPlan_TestCasesEntry> = {
              encode(
      message: TestPlan_TestCasesEntry,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
if ( message.key !== "") {
          writer.uint32(10).string(message.key);
        }
if (message.value !== undefined ) {
          TestCase.encode(message.value, writer.uint32(18).fork()).join();
        }
return writer;
},

decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): TestPlan_TestCasesEntry {
      const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
const message = createBaseTestPlan_TestCasesEntry();
while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
case 1: {
if (tag !== 10) {
        break;
      }
    
        message.key = reader.string();
continue; }
case 2: {
if (tag !== 18) {
        break;
      }
    
        message.value = TestCase.decode(reader, reader.uint32());
continue; }
}
if ((tag & 7) === 4 || tag === 0) {
        break;
      }
reader.skip(tag & 7);
}
return message;
},

fromJSON(object: any): TestPlan_TestCasesEntry {
      return {
key: isSet(object.key) ? globalThis.String(object.key)
        
          : "",
value: isSet(object.value) ? TestCase.fromJSON(object.value)
        
          : undefined,
};
},

toJSON(message: TestPlan_TestCasesEntry): unknown {
      const obj: any = {};
if ( message.key !== "") {
          obj.key = message.key;
        }
if (message.value !== undefined ) {
          obj.value = TestCase.toJSON(message.value);
        }
return obj;
},

create<I extends Exact<DeepPartial<TestPlan_TestCasesEntry>, I>>(base?: I): TestPlan_TestCasesEntry {
        return TestPlan_TestCasesEntry.fromPartial(base ?? ({} as any));
      },
fromPartial<I extends Exact<DeepPartial<TestPlan_TestCasesEntry>, I>>(object: I): TestPlan_TestCasesEntry {
const message = createBaseTestPlan_TestCasesEntry();
message.key = object.key ?? "";
message.value = (object.value !== undefined && object.value !== null)
          ? TestCase.fromPartial(object.value)
          : undefined;
return message;
}
            };

function createBaseWorkInstruction(): WorkInstruction {
      return { id: "",templateId: "",testPlanId: "",format: "",content: "",version: "",createdAt: "0",approvedBy: undefined,approvedAt: undefined };
    }

export const WorkInstruction: MessageFns<WorkInstruction> = {
              encode(
      message: WorkInstruction,
      writer: BinaryWriter = new BinaryWriter(),
    ): BinaryWriter {
if ( message.id !== "") {
          writer.uint32(10).string(message.id);
        }
if ( message.templateId !== "") {
          writer.uint32(18).string(message.templateId);
        }
if ( message.testPlanId !== "") {
          writer.uint32(26).string(message.testPlanId);
        }
if ( message.format !== "") {
          writer.uint32(34).string(message.format);
        }
if ( message.content !== "") {
          writer.uint32(42).string(message.content);
        }
if ( message.version !== "") {
          writer.uint32(50).string(message.version);
        }
if ( message.createdAt !== "0") {
          writer.uint32(56).int64(message.createdAt);
        }
if (message.approvedBy !== undefined ) {
          writer.uint32(66).string(message.approvedBy);
        }
if (message.approvedAt !== undefined ) {
          writer.uint32(72).int64(message.approvedAt);
        }
return writer;
},

decode(
      input: BinaryReader | Uint8Array,
      length?: number,
    ): WorkInstruction {
      const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
const message = createBaseWorkInstruction();
while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
case 1: {
if (tag !== 10) {
        break;
      }
    
        message.id = reader.string();
continue; }
case 2: {
if (tag !== 18) {
        break;
      }
    
        message.templateId = reader.string();
continue; }
case 3: {
if (tag !== 26) {
        break;
      }
    
        message.testPlanId = reader.string();
continue; }
case 4: {
if (tag !== 34) {
        break;
      }
    
        message.format = reader.string();
continue; }
case 5: {
if (tag !== 42) {
        break;
      }
    
        message.content = reader.string();
continue; }
case 6: {
if (tag !== 50) {
        break;
      }
    
        message.version = reader.string();
continue; }
case 7: {
if (tag !== 56) {
        break;
      }
    
        message.createdAt = reader.int64().toString();
continue; }
case 8: {
if (tag !== 66) {
        break;
      }
    
        message.approvedBy = reader.string();
continue; }
case 9: {
if (tag !== 72) {
        break;
      }
    
        message.approvedAt = reader.int64().toString();
continue; }
}
if ((tag & 7) === 4 || tag === 0) {
        break;
      }
reader.skip(tag & 7);
}
return message;
},

fromJSON(object: any): WorkInstruction {
      return {
id: isSet(object.id) ? globalThis.String(object.id)
        
          : "",
templateId: isSet(object.templateId) ? globalThis.String(object.templateId)
         : isSet(object.template_id) ? globalThis.String(object.template_id)
          : "",
testPlanId: isSet(object.testPlanId) ? globalThis.String(object.testPlanId)
         : isSet(object.test_plan_id) ? globalThis.String(object.test_plan_id)
          : "",
format: isSet(object.format) ? globalThis.String(object.format)
        
          : "",
content: isSet(object.content) ? globalThis.String(object.content)
        
          : "",
version: isSet(object.version) ? globalThis.String(object.version)
        
          : "",
createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt)
         : isSet(object.created_at) ? globalThis.String(object.created_at)
          : "0",
approvedBy: isSet(object.approvedBy) ? globalThis.String(object.approvedBy)
         : isSet(object.approved_by) ? globalThis.String(object.approved_by)
          : undefined,
approvedAt: isSet(object.approvedAt) ? globalThis.String(object.approvedAt)
         : isSet(object.approved_at) ? globalThis.String(object.approved_at)
          : undefined,
};
},

toJSON(message: WorkInstruction): unknown {
      const obj: any = {};
if ( message.id !== "") {
          obj.id = message.id;
        }
if ( message.templateId !== "") {
          obj.templateId = message.templateId;
        }
if ( message.testPlanId !== "") {
          obj.testPlanId = message.testPlanId;
        }
if ( message.format !== "") {
          obj.format = message.format;
        }
if ( message.content !== "") {
          obj.content = message.content;
        }
if ( message.version !== "") {
          obj.version = message.version;
        }
if ( message.createdAt !== "0") {
          obj.createdAt = message.createdAt;
        }
if (message.approvedBy !== undefined ) {
          obj.approvedBy = message.approvedBy;
        }
if (message.approvedAt !== undefined ) {
          obj.approvedAt = message.approvedAt;
        }
return obj;
},

create<I extends Exact<DeepPartial<WorkInstruction>, I>>(base?: I): WorkInstruction {
        return WorkInstruction.fromPartial(base ?? ({} as any));
      },
fromPartial<I extends Exact<DeepPartial<WorkInstruction>, I>>(object: I): WorkInstruction {
const message = createBaseWorkInstruction();
message.id = object.id ?? "";
message.templateId = object.templateId ?? "";
message.testPlanId = object.testPlanId ?? "";
message.format = object.format ?? "";
message.content = object.content ?? "";
message.version = object.version ?? "";
message.createdAt = object.createdAt ?? "0";
message.approvedBy = object.approvedBy ?? undefined;
message.approvedAt = object.approvedAt ?? undefined;
return message;
}
            };







type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> =  T extends Builtin
        ? T
        
        : T extends globalThis.Array<infer U>
        ? globalThis.Array<DeepPartial<U>>
        : T extends ReadonlyArray<infer U>
        ? ReadonlyArray<DeepPartial<U>>
        : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
      export type Exact<P, I extends P> = P extends Builtin
        ? P
        : P &
        { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P> >]: never };



















function isObject(value: any): boolean {
      return typeof value === 'object' && value !== null;
    }

function isSet(value: any): boolean {
      return value !== null && value !== undefined;
    }









export interface MessageFns<T> {
        encode(message: T, writer?: BinaryWriter): BinaryWriter;
decode(input: BinaryReader | Uint8Array, length?: number): T;
fromJSON(object: any): T;
toJSON(message: T): unknown;
create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
      }