# Allow writing specgen files in plan mode
[[rule]]
toolName = ["write_file", "replace"]
priority = 175 # prioritize over other extension policies
decision = "ask_user"
modes = ["plan"]
argsPattern = '"(?:file_path|path)":"specgen/[^"]*"'

# Allow tools used by specgen to set up conductor dir
[[rule]]
toolName = "run_shell_command"
commandPrefix = ["git status", "git diff", "ls", "mkdir", "cp", "git init", "git add", "git commit"]
decision = "ask_user"
priority = 200 # prioritize over other extension policies
modes = ["plan"]
